US[1] Added form
WildCodeSchool/purple-php-2109-project2-quizzy pull request #2
Opened 2021-11-03 12:30 UTC by MorganeL-pro

Create the form to show one question and its answers
(files to check : QuestionManager.php, QuestionController.php, AnswerManager.php, routes.php and twig views (index, answers + components)

2021-11-03 13:17 UTC, iStyyx submitted a review, later dismissed
Le fonctionnement est bon, le code a été vérifié sans erreurs.

2021-11-03 16:01 UTC, RomainClair requested changes
The / (index) and /answers HTML pages are invalid according to W3C validator.
US[1] is : "arriver sur un site beau, simple, facile d’utilisation"...
But according to the comments, it seems that this PR is about 3 US : 
1 - I can access the list of questions
2 - I can list the different possible answer of a question
3 - I can see information for a specific question.

PR should be atomic. i.e. : it should be about 1 US only

2021-11-03 16:01 UTC, RomainClair commented on src/Model/QuestionManager.php
> +    public function getRandomQuestion(): array
To be coherent with the AbstractManager, this method should probably be called selectRandomQuestion

2021-11-04 09:54 UTC, MorganeL-pro commented
We've changed the branch to show only the files used for [US1] feature "the user can see a page with a question and its answers displayed randomly.

2021-11-04 09:59 UTC, iStyyx approved these changes
It seems more clarly, no errors (Sniffer & W3C) and the feature is working for me.

2021-11-04 10:38 UTC, RomainClair reviewed
It's a bit strange to have 2 headers and 2 footer on a page.
I guess the idea is to have the nav on the top of the page or on the bottom depending of the user's device...
But wouldn't it be a better idea to just have a single header, footer and a nav outside header and footer and position the nav using CSS ?

2021-11-04 13:52 UTC, RomainClair approved these changes

2021-11-04 13:52 UTC, merged