Us5 never the same question
WildCodeSchool/purple-php-2109-project2-quizzy pull request #8
Opened 2021-11-14 19:35 UTC by MorganeL-pro

The user won't respond to the same question if he got the good answer the first time (the question ids are stocked in a session).
When he responds to every question in the website, he is redirected to a page where he can see the amount of good questions and can click on a button to play again (when the amount of good answers equals the amount of all the questions stocked on the database, the session array is unsetted).

2021-11-14 21:35 UTC, Benjamin-51 submitted a review, later dismissed
This work correctly on my end. Though if I refresh the answer page after I added correctly, it adds the question again in the questionsWellAnswered array.
The checkIfCorrect function in the question controller has to check for this.

2021-11-15 17:46 UTC, Benjamin-51 commented
Still works. Also worth mentioning my comment above isn't relevant in the long run since the question correctly answered will be saved in the database and will already have a duplicate protection.

2021-11-15 17:47 UTC, Benjamin-51 submitted a review, later dismissed

2021-11-16 14:00 UTC, RomainClair requested changes

2021-11-16 14:00 UTC, RomainClair commented on src/Controller/SuccessController.php
> +        $score = $_SESSION['score'];
Session index may not always be defined. You should check if defined before accessing it

2021-11-16 14:00 UTC, RomainClair commented on src/Controller/SuccessController.php
> +        self::unsetUserSession();
As unsetUserSession is a non static method, you shoud call it using $this->

2021-11-16 14:00 UTC, RomainClair commented on src/Model/AnswersManager.php
> +    }
This seems to be the AbstractManager::selectOneById method. You'd better use it rather than create a new method doing the same thing

2021-11-16 15:26 UTC, Benjamin-51 approved these changes
Sounds good to me.

2021-11-17 08:28 UTC, RomainClair approved these changes

2021-11-17 08:28 UTC, merged